### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocoevalcap'

### ISSUE THREAD

**Issue by crazybw** [clips/clicr#3]
Traceback (most recent call last):
  File "/home/machine_reading_comprehension/clicr-master/dataset/evaluate.py", line 176, in <module>
    embeddings_file=args.embeddings_file, downcase=args.downcase))
  File "/home/machine_reading_comprehension/clicr-master/dataset/evaluate.py", line 116, in evaluate
    from pycocoevalcap.eval import COCOEvalCap
ModuleNotFoundError: No module named 'pycocoevalcap'

**Comment by SimonSuster** [comment]
Fixed with commit f4db25d39f997806153784e3b4f2b9ae632bc899
